import type { AnthropicCalibration } from "./anthropic.js";

// generated by `token-sift calibrate anthropic run` against a real Anthropic
// API key and a dedicated fixture corpus (test/fixtures/calibration/anthropic-samples.json),
// not hand-tuned. Ratios are identical across all three current-generation models below
// because the calibration run measured identical results for each -- consistent with
// Anthropic sharing one tokenizer across the current Claude generation, not a fitting bug.
export const ANTHROPIC_CALIBRATIONS: Record<string, AnthropicCalibration> = {
  "claude-opus-4-5": {
    model: "claude-opus-4-5",
    ratios: {
      word: 5.189956301130032,
      punct: 2.0965650048629922,
      whitespace: 3.2414576403322726,
      "digit-fragment": 1.473950463406977,
      "hex-fragment": 1.7438817400743072,
      other: 2.566302029414443,
    },
    sampleCount: 28,
    measuredAt: "2026-07-22T18:05:30.414Z",
    meanAbsPercentError: 7.604063576014257,
  },
  "claude-sonnet-4-5": {
    model: "claude-sonnet-4-5",
    ratios: {
      word: 5.189956301130032,
      punct: 2.0965650048629922,
      whitespace: 3.2414576403322726,
      "digit-fragment": 1.473950463406977,
      "hex-fragment": 1.7438817400743072,
      other: 2.566302029414443,
    },
    sampleCount: 28,
    measuredAt: "2026-07-22T18:06:01.354Z",
    meanAbsPercentError: 7.604063576014257,
  },
  "claude-haiku-4-5": {
    model: "claude-haiku-4-5",
    ratios: {
      word: 5.189956301130032,
      punct: 2.0965650048629922,
      whitespace: 3.2414576403322726,
      "digit-fragment": 1.473950463406977,
      "hex-fragment": 1.7438817400743072,
      other: 2.566302029414443,
    },
    sampleCount: 28,
    measuredAt: "2026-07-22T18:06:09.298Z",
    meanAbsPercentError: 7.604063576014257,
  },
};
