// Fetches LiteLLM's model pricing table and writes a curated, filtered
// snapshot to src/pricing-data.ts. Manual/explicit only, matching this
// project's policy of never making a network call automatically: run this
// yourself with `pnpm pricing:update` when you want fresher prices, it's
// never invoked by build/test/CI.
//
// Source is MIT-licensed (Berri AI / LiteLLM), see LICENSE-THIRD-PARTY.md.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const SOURCE_URL =
  "https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json";

// Kept in sync by hand with src/encoders/registry.ts (OPENAI_MODEL_FAMILY)
// and src/encoders/anthropic-calibration.ts (ANTHROPIC_CALIBRATIONS): only
// pull pricing for models token-sift actually resolves an encoder for.
// o1-mini, chatgpt-4o-latest, and codex-mini-latest are deliberately absent:
// all three are in OPENAI_MODEL_FAMILY (gpt-tokenizer still ships their rank
// data) but LiteLLM no longer tracks pricing for them, retired/superseded.
// Finding.cost is undefined for them, same documented, expected case as any
// model with no bundled pricing row.
const SUPPORTED_MODELS = [
  "gpt-4o",
  "gpt-4o-mini",
  "gpt-4.1",
  "gpt-4.1-mini",
  "gpt-4.1-nano",
  "gpt-5",
  "gpt-5-mini",
  "gpt-5-nano",
  "gpt-5-pro",
  "gpt-5-chat-latest",
  "gpt-5-codex",
  "gpt-5.1",
  "gpt-5.2",
  "gpt-5.2-pro",
  "gpt-5.3-codex",
  "gpt-5.4",
  "gpt-5.4-pro",
  "gpt-5.4-mini",
  "gpt-5.4-nano",
  "gpt-5.5",
  "gpt-5.5-pro",
  "gpt-5.6-sol",
  "gpt-5.6-terra",
  "gpt-5.6-luna",
  "gpt-6-sol",
  "gpt-6-luna",
  "gpt-6.1-sol",
  "gpt-6-astra",
  "o1",
  "o1-pro",
  "o3",
  "o3-mini",
  "o3-pro",
  "o4-mini",
  "computer-use-preview",
  "gpt-4-turbo",
  "gpt-4",
  "gpt-3.5-turbo",
  "claude-opus-4-5",
  "claude-sonnet-4-5",
  "claude-haiku-4-5",
];

async function main() {
  const res = await fetch(SOURCE_URL);
  if (!res.ok) throw new Error(`fetch failed: ${res.status} ${res.statusText}`);
  const raw = await res.json();

  const rows = {};
  const missing = [];
  for (const model of SUPPORTED_MODELS) {
    const entry = raw[model];
    if (!entry || typeof entry.input_cost_per_token !== "number") {
      missing.push(model);
      continue;
    }
    rows[model] = {
      model,
      provider: entry.litellm_provider ?? "unknown",
      inputCostPerToken: entry.input_cost_per_token,
      outputCostPerToken: entry.output_cost_per_token ?? 0,
      ...(typeof entry.cache_read_input_token_cost === "number"
        ? { cacheReadInputCostPerToken: entry.cache_read_input_token_cost }
        : {}),
    };
  }

  if (missing.length > 0) {
    throw new Error(`LiteLLM data missing for supported models: ${missing.join(", ")}`);
  }

  const outPath = fileURLToPath(new URL("../src/pricing-data.ts", import.meta.url));
  const body = `import type { PricingRow } from "./pricing.js";

// Curated snapshot of LiteLLM's model pricing table, filtered to the models
// token-sift resolves an encoder for. Source: BerriAI/litellm (MIT), see
// LICENSE-THIRD-PARTY.md. Generated by scripts/update-pricing.mjs, not
// hand-tuned. Refresh with \`pnpm pricing:update\`.
//
// Snapshot date: ${new Date().toISOString()}
export const PRICING_DATA: Record<string, PricingRow> = ${JSON.stringify(rows, null, 2)};
`;

  writeFileSync(outPath, body);
  console.log(`wrote pricing data for ${Object.keys(rows).length} models to ${outPath}`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
